# Generated by Django 4.2.5 on 2023-09-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status_checked', models.BooleanField(verbose_name='Проверено?')),
                ('full_name', models.CharField(max_length=128, verbose_name='ИФО')),
                ('phone_number', models.CharField(max_length=64, verbose_name='Номер телефона')),
                ('date', models.DateTimeField(verbose_name='Дата и время приёма')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
            },
        ),
        migrations.CreateModel(
            name='FormFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status_checked', models.BooleanField(verbose_name='Проверено?')),
                ('full_name', models.CharField(max_length=128, verbose_name='ИФО')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='FormPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status_checked', models.BooleanField(verbose_name='Проверено?')),
                ('phone_number', models.CharField(max_length=64, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Форма номера телефона',
                'verbose_name_plural': 'Формы номера телефона',
            },
        ),
    ]
