# Generated by Django 4.2.5 on 2023-09-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfeedback',
            name='phone_number',
            field=models.CharField(default=None, max_length=64, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='formfeedback',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='formphone',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
    ]
