# Generated by Django 4.2.5 on 2023-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_formfeedback_phone_number_alter_booking_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_checked',
            field=models.BooleanField(default=False, verbose_name='Проверено?'),
        ),
        migrations.AlterField(
            model_name='formfeedback',
            name='status_checked',
            field=models.BooleanField(default=False, verbose_name='Проверено?'),
        ),
        migrations.AlterField(
            model_name='formphone',
            name='status_checked',
            field=models.BooleanField(default=False, verbose_name='Проверено?'),
        ),
    ]
