# Generated by Django 4.2.5 on 2023-10-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfeedback',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
