# Generated by Django 4.2.5 on 2023-10-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_formfeedback_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время конца')),
            ],
            options={
                'verbose_name': 'Сессия приёма',
                'verbose_name_plural': 'Сессии приёма',
                'ordering': ('time_start',),
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(verbose_name='Дата приёма'),
        ),
    ]
