# Generated by Django 4.2.5 on 2023-10-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clinic/specialist/photo', verbose_name='Фото'),
        ),
    ]
