# Generated by Django 4.2.5 on 2023-10-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_specialist_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('phone_raw', models.CharField(help_text='Используется для ссылки на звонок', max_length=32, verbose_name='Номер телефона (без спец. символов и пробелов)')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта клиники')),
                ('address', models.TextField(verbose_name='Адресс клиники')),
                ('address_link', models.TextField(verbose_name='Ссылка на адресс клиники')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
