# Generated by Django 4.2.5 on 2023-10-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_specialist_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'До и после (секция)',
                'verbose_name_plural': 'До и после (секции)',
            },
        ),
        migrations.CreateModel(
            name='BeforeAfterUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinic/before-after-unit/image/', verbose_name='Фотография до и после')),
                ('name', models.CharField(help_text='Не обязательно, не показывается нигде кроме админ панели', max_length=128, verbose_name='Название')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.beforeaftersection', verbose_name='Секция к которой принадлежит фото')),
            ],
            options={
                'verbose_name': 'До и после (фото)',
                'verbose_name_plural': 'До и после (фото)',
            },
        ),
    ]
