# Generated by Django 4.2.5 on 2023-10-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_beforeaftersection_beforeafterunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beforeafterunit',
            name='section',
        ),
        migrations.AddField(
            model_name='beforeaftersection',
            name='units',
            field=models.ManyToManyField(blank=True, to='clinic.beforeafterunit', verbose_name='Изображения'),
        ),
    ]
