# Generated by Django 4.2.5 on 2023-10-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_remove_beforeafterunit_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beforeaftersection',
            options={'ordering': ['id'], 'verbose_name': 'До и после (секция)', 'verbose_name_plural': 'До и после (секции)'},
        ),
        migrations.AlterModelOptions(
            name='beforeafterunit',
            options={'ordering': ['id'], 'verbose_name': 'До и после (фото)', 'verbose_name_plural': 'До и после (фото)'},
        ),
        migrations.AddField(
            model_name='specialist',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='Доп информация'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='about_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Доп информация'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Доп информация'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='full_name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='ИФО'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='full_name_fi',
            field=models.CharField(max_length=64, null=True, verbose_name='ИФО'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='full_name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='ИФО'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='position_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='position_fi',
            field=models.CharField(max_length=64, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='position_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Позиция'),
        ),
    ]
