# Generated by Django 4.2.5 on 2023-10-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_beforeaftersection_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='about_en',
            new_name='about_en_US',
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='full_name_en',
            new_name='full_name_en_US',
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='position_en',
            new_name='position_en_US',
        ),
    ]
