# Generated by Django 4.2.5 on 2023-10-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_rename_about_en_specialist_about_en_us_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='about_fi',
            new_name='about_fin',
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='full_name_fi',
            new_name='full_name_fin',
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='position_fi',
            new_name='position_fin',
        ),
    ]
