# Generated by Django 4.2.5 on 2023-10-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_rename_about_fi_specialist_about_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='about_en_US',
            new_name='about_en',
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='full_name_en_US',
            new_name='full_name_en',
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='position_en_US',
            new_name='position_en',
        ),
    ]
