# Generated by Django 4.2.5 on 2023-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=None, verbose_name='Короткий контент'),
            preserve_default=False,
        ),
    ]
