# Generated by Django 4.2.5 on 2023-10-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_name_en_us_category_name_fi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_fi',
            new_name='name_fin',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_fi',
            new_name='content_fin',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt_fi',
            new_name='excerpt_fin',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_fi',
            new_name='title_fin',
        ),
    ]
