# Generated by Django 4.2.5 on 2023-10-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_name_fi_category_name_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en_US',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_en_US',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt_en_US',
            new_name='excerpt_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_en_US',
            new_name='title_en',
        ),
    ]
