# Generated by Django 4.2.5 on 2023-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='starting_from',
            field=models.BooleanField(default=False, verbose_name='Начинается от?'),
        ),
    ]
