# Generated by Django 4.2.5 on 2023-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_price_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='title_en_US',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='price',
            name='title_fi',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='price',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en_US',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_fi',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
    ]
