# Generated by Django 4.2.5 on 2023-10-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_title_fi_price_title_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title_en_US',
            new_name='title_en',
        ),
    ]
