# Generated by Django 4.2.5 on 2023-10-31 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_price_prices_price_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.price', verbose_name='Родитель'),
        ),
    ]
