# Generated by Django 4.2.5 on 2023-10-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_answer_en_us_faq_answer_fi_faq_answer_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer_fi',
            new_name='answer_fin',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question_fi',
            new_name='question_fin',
        ),
    ]
