# Generated by Django 4.2.5 on 2023-10-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_rename_answer_fi_faq_answer_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer_en_US',
            new_name='answer_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question_en_US',
            new_name='question_en',
        ),
    ]
